### ISSUE TITLE
function should be camlized

### ISSUE THREAD

**Issue by pelikhan** [4tronix/MiniBit#2]
https://github.com/4tronix/MiniBit/blob/95b239b020eeeea0defe61c98ff03809c4a381b2/main.ts#L157

Avoid snake naming convention; maybe drop the "minibit_" here?

**Comment by 4tronix** [comment]
function renamed to stop

**Comment by pelikhan** [comment]
Make sure to bump again.

**Comment by 4tronix** [comment]
yes - just doing it...

------ Original Message ------
